name: swiftdrip
favicon: null
layout_spectrum: 0.99904
typography_spectrum: 0.21291
title: Learn Swift drip by drip
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1d393a'
    - '#ebdddc'
    - '#ad9990'
    - '#706f75'
    - '#45a6af'
  brandStrength: 0.875
  lightness: 0.7659437377005816
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
